name = "BeeBrewery"
uuid = "0bdfbc32-0cda-4ccb-afe5-7aaeaae9971f"
authors = ["Bhavya Goyal <bhavyagoyal.workday@gmail.com>"]
version = "1.0.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
